# Generated by Django 5.1.7 on 2025-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_address_tenant_country_tenant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
