site_name: naafi
site_description: Just another SaaS
repo_url: https://github.com/catdieng/backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/catdieng">catdieng</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
      - Authentication: 'api/authentication.md'
      - Users: 'api/users.md'
