# Generated by Django 5.1.7 on 2025-06-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
