# Generated by Django 5.1.7 on 2025-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_service_options_service_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
