# Generated by Django 5.1.7 on 2025-07-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_default_taxes'),
        ('services', '0003_alter_service_description'),
        ('taxes', '0002_rename_tax_type_tax_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('categories.category',),
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_taxes',
            field=models.ManyToManyField(blank=True, to='taxes.tax'),
        ),
    ]
