# Generated by Django 5.1.7 on 2025-07-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='tax_type',
            new_name='rate_type',
        ),
    ]
