# Generated by Django 5.1.7 on 2025-07-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_rename_tax_type_tax_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='rate_type',
            field=models.CharField(choices=[('percentages', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentages', max_length=11),
        ),
    ]
