# Generated by Django 5.1.7 on 2025-12-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_deleted_appointment_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('waiting_parts', 'Waiting parts'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20),
        ),
    ]
