/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExpensesRouteImport } from './routes/_layout/expenses'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutInvoicesIndexRouteImport } from './routes/_layout/invoices/index'
import { Route as LayoutInvoicesNewRouteImport } from './routes/_layout/invoices/new'
import { Route as LayoutInvoicesInvoiceIdEditRouteImport } from './routes/_layout/invoices_/$invoiceId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesRoute = LayoutExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesIndexRoute = LayoutInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesNewRoute = LayoutInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesInvoiceIdEditRoute =
  LayoutInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices_/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/customers': typeof LayoutCustomersRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/invoices/new': typeof LayoutInvoicesNewRoute
  '/invoices': typeof LayoutInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/customers': typeof LayoutCustomersRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/invoices/new': typeof LayoutInvoicesNewRoute
  '/invoices': typeof LayoutInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/expenses': typeof LayoutExpensesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/invoices/new': typeof LayoutInvoicesNewRoute
  '/_layout/invoices/': typeof LayoutInvoicesIndexRoute
  '/_layout/invoices_/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/categories'
    | '/customers'
    | '/expenses'
    | '/items'
    | '/profile'
    | '/settings'
    | '/users'
    | '/'
    | '/invoices/new'
    | '/invoices'
    | '/invoices/$invoiceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/categories'
    | '/customers'
    | '/expenses'
    | '/items'
    | '/profile'
    | '/settings'
    | '/users'
    | '/'
    | '/invoices/new'
    | '/invoices'
    | '/invoices/$invoiceId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/calendar'
    | '/_layout/categories'
    | '/_layout/customers'
    | '/_layout/expenses'
    | '/_layout/items'
    | '/_layout/profile'
    | '/_layout/settings'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/invoices/new'
    | '/_layout/invoices/'
    | '/_layout/invoices_/$invoiceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses': {
      id: '/_layout/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof LayoutExpensesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices/': {
      id: '/_layout/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof LayoutInvoicesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices/new': {
      id: '/_layout/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof LayoutInvoicesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices_/$invoiceId/edit': {
      id: '/_layout/invoices_/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof LayoutInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutExpensesRoute: typeof LayoutExpensesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutInvoicesNewRoute: typeof LayoutInvoicesNewRoute
  LayoutInvoicesIndexRoute: typeof LayoutInvoicesIndexRoute
  LayoutInvoicesInvoiceIdEditRoute: typeof LayoutInvoicesInvoiceIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutExpensesRoute: LayoutExpensesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutInvoicesNewRoute: LayoutInvoicesNewRoute,
  LayoutInvoicesIndexRoute: LayoutInvoicesIndexRoute,
  LayoutInvoicesInvoiceIdEditRoute: LayoutInvoicesInvoiceIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
