/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingRouteImport } from './routes/_layout/setting'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExpensesRouteImport } from './routes/_layout/expenses'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCustomersRouteImport } from './routes/_layout/customers'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutCalendarRouteImport } from './routes/_layout/calendar'
import { Route as LayoutInvoicesIndexRouteImport } from './routes/_layout/invoices/index'
import { Route as LayoutSettingsVehiclesBrandsRouteImport } from './routes/_layout/settings/vehicles-brands'
import { Route as LayoutSettingsUsersRouteImport } from './routes/_layout/settings/users'
import { Route as LayoutSettingsTaxesRouteImport } from './routes/_layout/settings/taxes'
import { Route as LayoutSettingsOrganizationRouteImport } from './routes/_layout/settings/organization'
import { Route as LayoutSettingsBillingRouteImport } from './routes/_layout/settings/billing'
import { Route as LayoutInvoicesNewRouteImport } from './routes/_layout/invoices/new'
import { Route as LayoutInvoicesInvoiceIdEditRouteImport } from './routes/_layout/invoices_/$invoiceId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingRoute = LayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesRoute = LayoutExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCustomersRoute = LayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarRoute = LayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesIndexRoute = LayoutInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsVehiclesBrandsRoute =
  LayoutSettingsVehiclesBrandsRouteImport.update({
    id: '/settings/vehicles-brands',
    path: '/settings/vehicles-brands',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsUsersRoute = LayoutSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsTaxesRoute = LayoutSettingsTaxesRouteImport.update({
  id: '/settings/taxes',
  path: '/settings/taxes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsOrganizationRoute =
  LayoutSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsBillingRoute = LayoutSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesNewRoute = LayoutInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvoicesInvoiceIdEditRoute =
  LayoutInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices_/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/customers': typeof LayoutCustomersRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/profile': typeof LayoutProfileRoute
  '/setting': typeof LayoutSettingRoute
  '/invoices/new': typeof LayoutInvoicesNewRoute
  '/settings/billing': typeof LayoutSettingsBillingRoute
  '/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/settings/taxes': typeof LayoutSettingsTaxesRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/settings/vehicles-brands': typeof LayoutSettingsVehiclesBrandsRoute
  '/invoices/': typeof LayoutInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof LayoutCalendarRoute
  '/categories': typeof LayoutCategoriesRoute
  '/customers': typeof LayoutCustomersRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/profile': typeof LayoutProfileRoute
  '/setting': typeof LayoutSettingRoute
  '/invoices/new': typeof LayoutInvoicesNewRoute
  '/settings/billing': typeof LayoutSettingsBillingRoute
  '/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/settings/taxes': typeof LayoutSettingsTaxesRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/settings/vehicles-brands': typeof LayoutSettingsVehiclesBrandsRoute
  '/invoices': typeof LayoutInvoicesIndexRoute
  '/invoices/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/calendar': typeof LayoutCalendarRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/expenses': typeof LayoutExpensesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/setting': typeof LayoutSettingRoute
  '/_layout/invoices/new': typeof LayoutInvoicesNewRoute
  '/_layout/settings/billing': typeof LayoutSettingsBillingRoute
  '/_layout/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/_layout/settings/taxes': typeof LayoutSettingsTaxesRoute
  '/_layout/settings/users': typeof LayoutSettingsUsersRoute
  '/_layout/settings/vehicles-brands': typeof LayoutSettingsVehiclesBrandsRoute
  '/_layout/invoices/': typeof LayoutInvoicesIndexRoute
  '/_layout/invoices_/$invoiceId/edit': typeof LayoutInvoicesInvoiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/items'
    | '/profile'
    | '/setting'
    | '/invoices/new'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/taxes'
    | '/settings/users'
    | '/settings/vehicles-brands'
    | '/invoices/'
    | '/invoices/$invoiceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/items'
    | '/profile'
    | '/setting'
    | '/invoices/new'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/taxes'
    | '/settings/users'
    | '/settings/vehicles-brands'
    | '/invoices'
    | '/invoices/$invoiceId/edit'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/calendar'
    | '/_layout/categories'
    | '/_layout/customers'
    | '/_layout/dashboard'
    | '/_layout/expenses'
    | '/_layout/items'
    | '/_layout/profile'
    | '/_layout/setting'
    | '/_layout/invoices/new'
    | '/_layout/settings/billing'
    | '/_layout/settings/organization'
    | '/_layout/settings/taxes'
    | '/_layout/settings/users'
    | '/_layout/settings/vehicles-brands'
    | '/_layout/invoices/'
    | '/_layout/invoices_/$invoiceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/setting': {
      id: '/_layout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof LayoutSettingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses': {
      id: '/_layout/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof LayoutExpensesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar': {
      id: '/_layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof LayoutCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices/': {
      id: '/_layout/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof LayoutInvoicesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/vehicles-brands': {
      id: '/_layout/settings/vehicles-brands'
      path: '/settings/vehicles-brands'
      fullPath: '/settings/vehicles-brands'
      preLoaderRoute: typeof LayoutSettingsVehiclesBrandsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/users': {
      id: '/_layout/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof LayoutSettingsUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/taxes': {
      id: '/_layout/settings/taxes'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof LayoutSettingsTaxesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/organization': {
      id: '/_layout/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof LayoutSettingsOrganizationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/billing': {
      id: '/_layout/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof LayoutSettingsBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices/new': {
      id: '/_layout/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof LayoutInvoicesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invoices_/$invoiceId/edit': {
      id: '/_layout/invoices_/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof LayoutInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCalendarRoute: typeof LayoutCalendarRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutExpensesRoute: typeof LayoutExpensesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSettingRoute: typeof LayoutSettingRoute
  LayoutInvoicesNewRoute: typeof LayoutInvoicesNewRoute
  LayoutSettingsBillingRoute: typeof LayoutSettingsBillingRoute
  LayoutSettingsOrganizationRoute: typeof LayoutSettingsOrganizationRoute
  LayoutSettingsTaxesRoute: typeof LayoutSettingsTaxesRoute
  LayoutSettingsUsersRoute: typeof LayoutSettingsUsersRoute
  LayoutSettingsVehiclesBrandsRoute: typeof LayoutSettingsVehiclesBrandsRoute
  LayoutInvoicesIndexRoute: typeof LayoutInvoicesIndexRoute
  LayoutInvoicesInvoiceIdEditRoute: typeof LayoutInvoicesInvoiceIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCalendarRoute: LayoutCalendarRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutExpensesRoute: LayoutExpensesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSettingRoute: LayoutSettingRoute,
  LayoutInvoicesNewRoute: LayoutInvoicesNewRoute,
  LayoutSettingsBillingRoute: LayoutSettingsBillingRoute,
  LayoutSettingsOrganizationRoute: LayoutSettingsOrganizationRoute,
  LayoutSettingsTaxesRoute: LayoutSettingsTaxesRoute,
  LayoutSettingsUsersRoute: LayoutSettingsUsersRoute,
  LayoutSettingsVehiclesBrandsRoute: LayoutSettingsVehiclesBrandsRoute,
  LayoutInvoicesIndexRoute: LayoutInvoicesIndexRoute,
  LayoutInvoicesInvoiceIdEditRoute: LayoutInvoicesInvoiceIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
