# Generated by Django 5.1.7 on 2025-07-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_created_at_category_updated_at'),
        ('taxes', '0002_rename_tax_type_tax_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_taxes',
            field=models.ManyToManyField(blank=True, to='taxes.tax'),
        ),
    ]
